### ISSUE TITLE
docker image immediately exited after run

### ISSUE THREAD

**Issue by oxfordhalfblood** [varunon9/getting-started-docker-mysql-nodejs#1]
<img width="456" alt="Screen Shot 2019-12-16 at 1 34 51 pm" src="https://user-images.githubusercontent.com/20450604/70875236-5d47c300-2009-11ea-8f5a-10f000b0882d.png">

I followed your steps. But when I do step-9 and do docker ps the nodejs container is not showed. After checking the logs it shows me as the screenshot.

**Comment by varunon9** [comment]
Do you have express module in your package.json?
I think you are missing step-5. You can use this [package.json](https://github.com/varunon9/getting-started-docker-mysql-nodejs/blob/master/nodejs-microservice/package.json)-

**Comment by oxfordhalfblood** [comment]
I do have express in my package.json. This file was created by npm init and whenever I installed a new package. Below is my package.json:
 
{
  "name": "paloit",
  "version": "1.0.0",
  "description": "",
  "main": "server.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "node server.js"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "arraylist": "^0.1.0",
    "avl": "^1.4.4",
    "body-parser": "^1.19.0",
    "cheerio": "^1.0.0-rc.3",
    "ejs": "^3.0.1",
    "express": "^4.17.1",
    "hashmap": "^2.4.0",
    "hashtable": "git+https://github.com/fabrice102/node-hashtable.git",
    "jquery": "^3.4.1",
    "jsdom": "^15.2.1",
    "morgan": "^1.9.1",
    "multimap": "^1.1.0",
    "mysql": "^2.17.1",
    "request": "^2.88.0",
    "sort-map": "^1.0.0",
    "sorted-map": "^0.1.8",
    "yargs": "^15.0.2"
  }
}

**Comment by varunon9** [comment]
Error says that `cannot find module express` which means you must have missed `npm install` but this should not be the case if you have followed all the steps correctly.

**Comment by oxfordhalfblood** [comment]
Solved: The problem was in my package.json indeed. I was missing express. Also arraylist was with small 'a' and in my server.js it was require('Arraylist') which created the conflict. Thank u.
